import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from "./components/layout/navBar";
import Footer from "./components/sections/footer";
import SubscribeSection from "./components/sections/subscribeSection";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NavBar />
        {children}
        <SubscribeSection />
        <Footer />

        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function () {
        const theme = localStorage.getItem("theme");
        const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
        if (theme === "dark" || (!theme && prefersDark)) {
          document.documentElement.classList.add("dark");
        } else {
          document.documentElement.classList.remove("dark");
        }
      })();
    `,
          }}
        ></script>
      </body>
    </html>
  );
}
