import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./components/sections/Footer";
import NavBar from "./components/nav/NavBar";
import "./globals.css";

const poppins = Poppins({ weight: ["300", "400", "700", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NavBar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
